### ISSUE TITLE
JSON Output Directory not Created

### ISSUE THREAD

**Issue by applebyter** [BraeWebb/chalkbox#18]
If the JSON output directory specified in the BOX file does not exist, it is not created and the program finishes with an error message and outputting the JSON to stdout.

- [x] My preference would be for it to create the JSON output directory if it does not exist.
- [x] I would also like it to provide a warning, before processing the files, if there are files in the JSON output directory that are likely to be overwritten.

**Comment by BraeWebb** [comment]
All tasks have been completed but a followup task has been spawned #22 to re-introduce a variant of chalkbox that runs without prompts.
